---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  destinations:
  - name: "in-cluster"
    namespace: "*"
    server: "https://kubernetes.default.svc"
  sourceNamespaces:
  - argocd
  sourceRepos:
  - "*"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-apps
spec:
  generators:
  - git:
      directories:
      - path: common/all/*
      repoURL: https://github.com/myoung34/argocd-agent-autonomous-demo
      revision: HEAD
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: default
      revisionHistoryLimit: 5
      source:
        path: common/all/{{ path.basename }}
        repoURL: https://github.com/myoung34/argocd-agent-autonomous-demo.git
        targetRevision: HEAD
      syncPolicy:
        preserveResourcesOnDeletion: true
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - ServerSideApply=true
        - FailOnSharedResource=true
        - RespectIgnoreDifferences=true
        - SkipDryRunOnMissingResource=true
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - git:
      repoURL: 'https://github.com/myoung34/argocd-agent-autonomous-demo'
      revision: HEAD
      directories: []
  template:
    metadata:
      name: "{{ path.basename }}"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/myoung34/argocd-agent-autonomous-demo.git'
        targetRevision: HEAD
        path: ""
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        preserveResourcesOnDeletion: true
        syncOptions:
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - SkipDryRunOnMissingResource=true
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      revisionHistoryLimit: 5
